# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Tipo', models.IntegerField(max_length=5)),
                ('Dias_Act', models.CharField(max_length=45)),
                ('Rango_Edad', models.CharField(max_length=45)),
            ],
        ),
    ]
