# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Tipo',
        ),
    ]
