# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_auto_20180507_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='aaaaa', max_length=50)),
                ('Puesto', models.CharField(default='asssss', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Dias_Act',
            new_name='DiasAct',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Rango_Edad',
            new_name='Rangoedad',
        ),
        migrations.AddField(
            model_name='activity',
            name='Instructor',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Empleados'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Type',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Tiposact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Ubicacion',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Ubicacion'),
        ),
    ]
