# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20180507_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tiposact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='id',
        ),
        migrations.AddField(
            model_name='activity',
            name='ID',
            field=models.AutoField(default='123', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empleados',
            name='ID',
            field=models.AutoField(default='123', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tiposact',
            name='ID',
            field=models.AutoField(default='123', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ID',
            field=models.AutoField(default='123', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Puesto',
            field=models.CharField(max_length=50),
        ),
    ]
