# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_auto_20180507_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('Id', models.AutoField(default='123', editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('DiasAct', models.CharField(max_length=45)),
                ('Rangoedad', models.CharField(max_length=45)),
                ('Instructor', models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Empleados')),
                ('Type', models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Tiposact')),
                ('Ubica', models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='Activities.Ubicacion')),
            ],
        ),
    ]
