# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='hora_apertura',
            field=models.TimeField(verbose_name=b'Hora de apertura'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='hora_cierre',
            field=models.TimeField(verbose_name=b'Hora de cierre'),
        ),
    ]
