# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20180607_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasenia',
            field=models.CharField(max_length=16, null=True, verbose_name=b'Contrasenia del cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_de_usuario',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name=b'Nombre de usuario'),
        ),
    ]
